let firstName  = 'Fulano'
let lastName = 'Beltrano'
let country = 'Japao'
let city = 'tokio'
let age = 25
let isMarried = false
let year = new Date(2023)
console.log('TypeOf: ')
console.log(typeof(firstName))
console.log(typeof(lastName))
console.log(typeof(country))
console.log(typeof(city))
console.log(typeof(age))
console.log(typeof(isMarried))
console.log(typeof(year))
console.log(typeof('10')==typeof(10))
console.log(parseInt('9.81')==10)
console.log('Bool: ')
console.log(4 > 3)
console.log(4 >= 3)
console.log(4 < 3)
console.log(4 <= 3)
console.log(4 == 4)
console.log(4 === 4)
console.log(4 != 4)
console.log(4 !== 4)
console.log(4 != '4')
console.log(4 == '4')
console.log(4 === '4')
console.log('python and jargon'.length<4)
console.log('And(&&) or(||) ! ')
console.log(4 > 3 && 10 < 12)
console.log(4 > 3 && 10 > 12)
console.log(4 > 3 || 10 < 12)
console.log(4 > 3 || 10 > 12)
console.log(!(4 > 3))
console.log(!(4 < 3))
console.log(!(false))
console.log(!(4 > 3 && 10 < 12))
console.log(!(4 > 3 && 10 > 12))
console.log(!(4 === '4'))
console.log (('dragon and python'.substr(0,6)).includes('on') && ('dragon and python'.substr(11,)).includes('on'))
let data = new Date()
console.log(data)
console.log(data.getFullYear())
console.log(data.getMonth()+1)
console.log(data.getDate())
console.log(data.getDay()+1)
console.log(data.getHours())
console.log(data.getMinutes())
console.log(data.getSeconds())
console.log(data.getMilliseconds())
console.log(data.getTime()/1000)